# See https://github.com/caksoylar/keymap-drawer for more info
name: Draw ZMK keymaps
on:
  workflow_dispatch: # can be triggered manually
  push: # automatically run on changes to following paths
    paths:
      - 'config/*.keymap'
      - 'config/*.dtsi'
      - 'keymap_drawer.config.yaml'
      # - 'boards/*/*/*.keymap'

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      # Commit message for the commit that will be made by the workflow
      commit_message: '[Draw] ${{ github.event.head_commit.message }}'
      # path to the keymaps to parse
      keymap_patterns: 'config/*.keymap'
      # config file, ignored if not exists
      config_path: 'keymap_drawer.config.yaml'
      # path to save produced SVG and keymap YAML files
      output_folder: 'keymap-drawer'
      # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      parse_args: ''
      # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
      draw_args: ''
